const OpenedPokedexActionTypes = {
  FETCH_DETAILSDATA_START: 'FETCH_DETAILSDATA_START',
  FETCH_DETAILSDATA_SUCCESS: 'FETCH_DETAILSDATA_SUCCESS',
  FETCH_DETAILSDATA_FAILURE: 'FETCH_DETAILSDATA_FAILURE',
  SET_ONMOUSEOVER_ACTION: 'SET_ONMOUSEOVER_ACTION',
};

export default OpenedPokedexActionTypes;
