const ClosedPokedexActionTypes = {
  FETCH_DATA_START: 'FETCH_DATA_START',
  FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
  FETCH_DATA_FAILURE: 'FETCH_DATA_FAILURE',
  SET_PAGENUMBER_ACTION: 'SET_PAGENUMBER_ACTION',
  SET_CURRENTPAGE_ACTION: 'SET_CURRENTPAGE_ACTION',
};

export default ClosedPokedexActionTypes;
